apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: omnimfa-hpa
  namespace: omnimfa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70