apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-depl
  namespace: omnimfa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-depl
  template:
    metadata:
      labels:
        app: kafka-depl
    spec:
      containers:
        - name: kafka-container
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-k8ssvc:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://kafka-k8ssvc:9092,OUTSIDE://kafka-k8ssvc:9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-k8ssvc
  namespace: omnimfa
spec:
  type: ClusterIP
  ports:
    - name: inside
      port: 9092
      targetPort: 9092
    - name: outside
      port: 9093
      targetPort: 9093
  selector:
    app: kafka-depl