apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: omnimfa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omnimfa-secret
                  key: MYSQL-PASSWORD
            - name: MYSQL-DATABASE
              value: "main"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: omnimfa
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql