spring:
  config:
    activate:
      on-profile: prod

  application:
    name: onboarding-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE-URL}
    username: ${DATASOURCE-USERNAME}
    password: ${DATASOURCE-PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  kafka:
    bootstrap-servers: ${KAFKA-BOOTSTRAP-SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: AWS_MSK_IAM
        jaas:
          config: software.amazon.msk.auth.iam.IAMLoginModule required;
        client:
          callback:
            handler:
              class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

management:
  endpoints:
    web:
      exposure:
        include: health

eureka:
  client:
    enabled: false